# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PocketFlip
logo-url: "images/logo-icon.svg"
description: "Flip Tasks Into Free Rewards"
baseurl: "" # the subpath of your site, e.g. /blog
url: http://www.pocketflip.com



# Site Owner
owner:
  name: "Pocket Flip"
  email: "info@pocketfilp.com"
  google:
    analytics:
    verify:
  bing:
    verify:
  alexa:
    verify:
  yandex:
    verify:
  bio:
  avatar:



# Jekyll config
markdown: kramdown
include:
  # - .htaccess
  - _pages
exclude:
    - Gemfile
    - Gemfile.lock
    - Guardfile
    - s3_website.yml

# Local server config
host: 0.0.0.0

# Collectsions
# collections:
#   projects:
#     output: true
#     permalink: /:collection/:path/



# Defaults

defaults:

  # Pages
  - scope:
      path: _pages
      type: pages
    values:
      layout: default



# Jakyll assets
assets:
  # debug: false
  # css_compressor: sass
  sources:
    - _assets/javascripts
    - _assets/stylesheets
  autoprefixer:
    browsers: ["last 2 versions","> 5%","IE 9"]



# Gems
gems:
  - jekyll-sitemap
